/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.swingEvidence3;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormValidation extends javax.swing.JFrame {

    String ex;

    /**
     * Creates new form FormValidation
     */
    public FormValidation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1Id = new javax.swing.JTextField();
        jTextField2Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3Age = new javax.swing.JTextField();
        jTextField4Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Display = new javax.swing.JTable();
        jLabelMsg = new javax.swing.JLabel();
        jRadioButton1Male = new javax.swing.JRadioButton();
        jRadioButton2Female = new javax.swing.JRadioButton();
        jCheckBox1HTML = new javax.swing.JCheckBox();
        jCheckBox2Java = new javax.swing.JCheckBox();
        jCheckBox3Swing = new javax.swing.JCheckBox();
        jComboBox1Round = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1Msg = new javax.swing.JTextArea();
        jButton1Add = new javax.swing.JButton();
        jButton2ClearForm = new javax.swing.JButton();
        jButton3ClearTable = new javax.swing.JButton();
        jButton4Exit = new javax.swing.JButton();
        jButton5ReadFromFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Student Information");

        jLabel2.setText("Id");

        jTextField1Id.setText("0");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        jTextField3Age.setText("0");

        jLabel5.setText("Email");

        jLabel7.setText("Gender");

        jLabel8.setText("C.Course");

        jLabel9.setText("Round");

        jLabel10.setText("Comments");

        jTable1Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Age", "Email", "Gender", "C.Course", "Round", "Comments"
            }
        ));
        jScrollPane1.setViewportView(jTable1Display);

        buttonGroup1.add(jRadioButton1Male);
        jRadioButton1Male.setText("Male");

        buttonGroup1.add(jRadioButton2Female);
        jRadioButton2Female.setText("Female");

        jCheckBox1HTML.setText("HTML");

        jCheckBox2Java.setText("Java");

        jCheckBox3Swing.setText("Swing");

        jComboBox1Round.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Round", "Round-37", "Round-38", "Round-39", "Round-40" }));

        jTextArea1Msg.setColumns(20);
        jTextArea1Msg.setRows(5);
        jScrollPane2.setViewportView(jTextArea1Msg);

        jButton1Add.setText("Add");
        jButton1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddActionPerformed(evt);
            }
        });

        jButton2ClearForm.setText("Clear Form");
        jButton2ClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ClearFormActionPerformed(evt);
            }
        });

        jButton3ClearTable.setText("Clear Table");
        jButton3ClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ClearTableActionPerformed(evt);
            }
        });

        jButton4Exit.setText("Exit");
        jButton4Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ExitActionPerformed(evt);
            }
        });

        jButton5ReadFromFile.setText("Read From File");
        jButton5ReadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ReadFromFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3ClearTable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4Exit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1Male, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2Female))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCheckBox1HTML, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox2Java, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox3Swing, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1Round, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1Add, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2ClearForm))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField1Id, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField3Age, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField4Email, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButton5ReadFromFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1Male)
                            .addComponent(jRadioButton2Female)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1HTML)
                            .addComponent(jCheckBox2Java)
                            .addComponent(jCheckBox3Swing))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1Round, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Add)
                    .addComponent(jButton2ClearForm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3ClearTable)
                    .addComponent(jButton4Exit))
                .addGap(18, 18, 18)
                .addComponent(jButton5ReadFromFile)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean cE(String email) {
        int atpos = email.indexOf("@");
        int dotpos = email.lastIndexOf(".");
        if (atpos > 1 && (dotpos - atpos) > 2 && dotpos < email.length()) {
            // System.out.println("Valid email");
            return true;
        } else {
            // System.out.println("invalid email");
            return false;
        }

    }


    private void jButton1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddActionPerformed
        // TODO add your handling code here:

        //Id
        if (jTextField1Id.getText().trim().length() < 5) {
            JOptionPane.showMessageDialog(null, "Enter your Id number");

            //name   
        } else if (jTextField2Name.getText().trim().length() < 4) {
            JOptionPane.showMessageDialog(null, "Enter your Name");

            //age  
        } else if (Integer.parseInt(jTextField3Age.getText()) < 18 || Integer.parseInt(jTextField3Age.getText()) > 100) {
            JOptionPane.showMessageDialog(null, "Enter your Age between 18 to 100");

            //email
        } else if (!cE(jTextField4Email.getText()) || jTextField4Email.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your Email");

            //gender
        } else if (jRadioButton1Male.isSelected() == false && jRadioButton2Female.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Select your Gender");

            //course
        } else if (!jCheckBox1HTML.isSelected() && !jCheckBox2Java.isSelected() && !jCheckBox3Swing.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select your course");

            //round
        } else if (jComboBox1Round.getItemAt(jComboBox1Round.getSelectedIndex()).trim().equalsIgnoreCase("Select A Round")) {
            JOptionPane.showMessageDialog(null, "Select your round");
            //comments 
        } else if (jTextArea1Msg.getText().trim().length() < 10) {
            JOptionPane.showMessageDialog(null, "At least 10 characters");

        } else {

            int id = Integer.parseInt(jTextField1Id.getText());
            String name = jTextField2Name.getText();
            int age = Integer.parseInt(jTextField3Age.getText());
            String email = jTextField4Email.getText();

            String gender = " ";
            if (jRadioButton1Male.isSelected()) {
                gender = jRadioButton1Male.getText();
            }
            if (jRadioButton2Female.isSelected()) {
                gender = jRadioButton2Female.getText();
            }

            String course = " ";
            if (jCheckBox1HTML.isSelected()) {
                course += " " + jCheckBox1HTML.getText();
            }
            if (jCheckBox2Java.isSelected()) {
                course += " " + jCheckBox2Java.getText();
            }
            if (jCheckBox3Swing.isSelected()) {
                course += " " + jCheckBox3Swing.getText();
            }

            String round = jComboBox1Round.getItemAt(jComboBox1Round.getSelectedIndex());
            String comments = jTextArea1Msg.getText();

            String result = id + "\n" + name + "\n" + age + "\n" + email + "\n" + gender
                    + "\n" + course + "\n" + round + "\n" + comments;
            System.out.println(result);
            System.out.println("====================");
            
            DefaultTableModel model = (DefaultTableModel) jTable1Display.getModel();
            Object[] row = new Object[8];
            row[0] = id;
            row[1] = name;
            row[2] = age;
            row[3] = email;
            row[4] = gender;
            row[5] = course;
            row[6] = round;
            row[7] = comments;
            model.addRow(row);

            Student s = new Student(id, name, age, email, gender, course, round, comments);
            List<Student> list = new ArrayList<>();
            list.add(s);

            try {
                Utils.writeToFile("AbdulMotin", list);
            } catch (Exception e) {
                Logger.getLogger(FormValidation.class.getName()).log(Level.SEVERE, ex);
            }
            jLabelMsg.setText("Succesfully added int table and write to file ");
        }
    }//GEN-LAST:event_jButton1AddActionPerformed

    private void jButton2ClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ClearFormActionPerformed
        // TODO add your handling code here:
        jTextField1Id.setText("0");
        jTextField2Name.setText("");
        jTextField3Age.setText("0");
        jTextField4Email.setText("");
        buttonGroup1.clearSelection();
        jCheckBox1HTML.setSelected(false);
        jCheckBox2Java.setSelected(false);
        jCheckBox3Swing.setSelected(false);
        jComboBox1Round.setSelectedIndex(0);
        jTextArea1Msg.setText("");

    }//GEN-LAST:event_jButton2ClearFormActionPerformed

    private void jButton3ClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ClearTableActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1Display.getModel();
        model.setRowCount(0);

    }//GEN-LAST:event_jButton3ClearTableActionPerformed

    private void jButton4ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ExitActionPerformed

    private void jButton5ReadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ReadFromFileActionPerformed
        // TODO add your handling code here:
        String columns[] = {"id", "name", "age ", "email", "gender", "course", "round", "comments"};
        DefaultTableModel tableModel = new DefaultTableModel(0, 8);
        tableModel.setColumnIdentifiers(columns);
        jTable1Display.setModel(tableModel);
        Utils.displayStudentDataFromFile("AbdulMotin", tableModel);

    }//GEN-LAST:event_jButton5ReadFromFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormValidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1Add;
    private javax.swing.JButton jButton2ClearForm;
    private javax.swing.JButton jButton3ClearTable;
    private javax.swing.JButton jButton4Exit;
    private javax.swing.JButton jButton5ReadFromFile;
    private javax.swing.JCheckBox jCheckBox1HTML;
    private javax.swing.JCheckBox jCheckBox2Java;
    private javax.swing.JCheckBox jCheckBox3Swing;
    private javax.swing.JComboBox<String> jComboBox1Round;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JRadioButton jRadioButton1Male;
    private javax.swing.JRadioButton jRadioButton2Female;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1Display;
    private javax.swing.JTextArea jTextArea1Msg;
    private javax.swing.JTextField jTextField1Id;
    private javax.swing.JTextField jTextField2Name;
    private javax.swing.JTextField jTextField3Age;
    private javax.swing.JTextField jTextField4Email;
    // End of variables declaration//GEN-END:variables
}
